name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2.3.4

      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # - name: 👷‍ Install Dot and pandoc
      #   run: |
      #     conda install -c conda-forge pandoc
      #     conda install -c conda-forge ipython
      #     pip install sphinxcontrib-websupport
      #     sudo apt update
      #     sudo apt install -y graphviz

      - name: 👷‍ Install dependencies
        shell: bash
        run: |
          pip install --upgrade pip
          pip install .[doc]

      - name: 🔧 Build HTML
        run: |
          inv doc

      - name: 🚀 Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
